### ISSUE TITLE
Missing import of HTTPHandler

### ISSUE THREAD

**Issue by pv** [NeuralEnsemble/parameters#5]
There's a missing import for `HTTPHandler` here: https://github.com/NeuralEnsemble/parameters/blob/master/parameters/__init__.py#L87
Results to import failure of the module if `http_proxy` is defined in the environment (which breaks e.g. Sumatra).

**Comment by otitaud** [comment]
I unset the environment variable HTTP_PROXY:
unset HTTP_PROXY
But I am not sure it solves the problem deeply.

**Comment by pv** [comment]
The wontfix tag is not understandable --- it's a simple bug.

If this package is abandoned, that could be said explicitly.

**Comment by apdavison** [comment]
The package is not abandoned. @laurentperrinet what was the thinking in closing this?
